# .github/workflows/deploy.yml

name: Local Docker Deployment

on:
  push:
    paths:
      - '**.ps1'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PowerShell (if not already installed)
      run: |
        if ! command -v pwsh &> /dev/null; then
          echo "Installing PowerShell..."
          wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
        else
          echo "PowerShell already installed."
        fi

    - name: Run PowerShell script
      run: pwsh Hi_Script.ps1

    - name: Pull and run Docker container
      run: |
        echo 'FROM python:3.10-slim' > Dockerfile
        echo 'CMD echo "HI ZAYED THIS IS AFTER COMMIT"' >> Dockerfile
        docker build -t zayed-image .
        docker run --rm zayed-image





