name: Fetch License on Push

on:
  push:
    branches:
      - main

jobs:
  get-license:
    runs-on: self-hosted

    steps:
      - name: Call API and save license
        run: |
          cred="Admin:Admin"
          encodedCred=$(echo -n "$cred" | base64)

          # Fetch license and save it as license.txt
          curl -s -X GET "http://192.168.128.128/api/v1/license" \
            -H "Authorization: Basic $encodedCred" \
            -o license.txt

      - name: Upload license as artifact
        uses: actions/upload-artifact@v4
        with:
          name: license
          path: license.txt
